@extends('layouts.app')
@section('title', 'الإعدادات')
@section('content')
<div class="max-w-4xl mx-auto space-y-6" dir="rtl" x-data="{ activeTab: 'shop', testing: false, testResult: null, testingTg: false, testResultTg: null }">
    <h1 class="text-2xl font-extrabold text-white">الإعدادات</h1>
    <div class="stat-card rounded-2xl border overflow-hidden" style="border-color:var(--border)">
        <div class="flex border-b overflow-x-auto" style="border-color:var(--border)">
            <button @click="activeTab = 'shop'" :class="activeTab === 'shop' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'shop' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">المتجر</button>
            <button @click="activeTab = 'facebook'" :class="activeTab === 'facebook' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'facebook' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">فيسبوك بيكسل</button>
            <button @click="activeTab = 'shipping'" :class="activeTab === 'shipping' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'shipping' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">الشحن</button>
            <button @click="activeTab = 'dhd'" :class="activeTab === 'dhd' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'dhd' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">Ecotrack</button>
            <button @click="activeTab = 'telegram'" :class="activeTab === 'telegram' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'telegram' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">تيليجرام</button>
            <button @click="activeTab = 'account'" :class="activeTab === 'account' ? 'border-b-2' : ''" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" :style="activeTab === 'account' ? 'color:#4f8cff;border-bottom-color:#4f8cff' : 'color:var(--text-secondary)'">الحساب</button>
            <a href="{{ route('dashboard.settings.wilayaRates') }}" class="px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap" style="color:var(--text-secondary)">الشحن حسب الولاية</a>
        </div>
        <form action="{{ route('dashboard.settings.update') }}" method="POST" enctype="multipart/form-data" class="p-6">
            @csrf @method('PUT')
            <div x-show="activeTab === 'shop'" class="space-y-5">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">اسم المتجر *</label><input type="text" name="name" value="{{ old('name', $shop->name ?? '') }}" required class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">@error('name')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                    <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">رابط المتجر</label><input type="text" value="{{ $shop->slug ?? '' }}" class="w-full rounded-xl px-4 py-2.5 text-sm" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-tertiary)" dir="ltr" disabled></div>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">هاتف المتجر *</label><input type="text" name="phone" value="{{ old('phone', $shop->phone ?? '') }}" required class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr" placeholder="0555123456">@error('phone')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                    <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">الولاية *</label>
                        <select name="wilaya" required class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">
                            <option value="">اختر الولاية</option>
                            @php $allWilayas = ['01'=>'Adrar','02'=>'Chlef','03'=>'Laghouat','04'=>'Oum El Bouaghi','05'=>'Batna','06'=>'Béjaïa','07'=>'Biskra','08'=>'Béchar','09'=>'Blida','10'=>'Bouira','11'=>'Tamanrasset','12'=>'Tébessa','13'=>'Tlemcen','14'=>'Tiaret','15'=>'Tizi Ouzou','16'=>'Alger','17'=>'Djelfa','18'=>'Jijel','19'=>'Sétif','20'=>'Saïda','21'=>'Skikda','22'=>'Sidi Bel Abbès','23'=>'Annaba','24'=>'Guelma','25'=>'Constantine','26'=>'Médéa','27'=>'Mostaganem','28'=>'M\'Sila','29'=>'Mascara','30'=>'Ouargla','31'=>'Oran','32'=>'El Bayadh','33'=>'Illizi','34'=>'Bordj Bou Arreridj','35'=>'Boumerdès','36'=>'El Tarf','37'=>'Tindouf','38'=>'Tissemsilt','39'=>'El Oued','40'=>'Khenchela','41'=>'Souk Ahras','42'=>'Tipaza','43'=>'Mila','44'=>'Aïn Defla','45'=>'Naâma','46'=>'Aïn Témouchent','47'=>'Ghardaïa','48'=>'Relizane','49'=>'Timimoun','50'=>'Bordj Badji Mokhtar','51'=>'Ouled Djellal','52'=>'Beni Abbes','53'=>'In Salah','54'=>'In Guezzam','55'=>'Touggourt','56'=>'Djanet','57'=>'El M\'Ghair','58'=>'El Meniaa']; @endphp
                            @foreach($allWilayas as $code => $name)<option value="{{ $name }}" {{ ($shop->wilaya ?? '') === $name ? 'selected' : '' }}>{{ $code }} - {{ $name }}</option>@endforeach
                        </select>
                        @error('wilaya')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror
                    </div>
                </div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">العنوان</label><input type="text" name="address" value="{{ old('address', $shop->address ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">@error('address')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">البلدية</label><input type="text" name="commune" value="{{ old('commune', $shop->commune ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">@error('commune')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">شعار المتجر</label>
                    @if($shop->logo ?? false)<div class="mb-2"><img src="{{ asset('storage/' . $shop->logo) }}" alt="Logo" class="w-20 h-20 rounded-xl object-cover" style="border:1px solid var(--border)"></div>@endif
                    <input type="file" name="logo" accept="image/*" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">
                </div>
            </div>
            <div x-show="activeTab === 'facebook'" x-cloak class="space-y-5">
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">Facebook Pixel ID</label><input type="text" name="facebook_pixel_id" value="{{ old('facebook_pixel_id', $shop->facebook_pixel_id ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr">@error('facebook_pixel_id')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">Access Token</label><input type="password" name="access_token" value="{{ old('access_token', $shop->access_token ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr">@error('access_token')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">API Version</label>
                    <select name="api_version" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">
                        @foreach(['v19.0', 'v18.0', 'v17.0', 'v16.0'] as $version)<option value="{{ $version }}" {{ ($shop->api_version ?? 'v19.0') === $version ? 'selected' : '' }}>{{ $version }}</option>@endforeach
                    </select>
                </div>
            </div>
            <div x-show="activeTab === 'shipping'" x-cloak class="space-y-5">
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">تكلفة التوصيل الافتراضية (DA)</label><input type="number" name="default_shipping_cost" step="0.01" min="0" value="{{ old('default_shipping_cost', $shop->default_shipping_cost ?? 600) }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">@error('default_shipping_cost')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
            </div>
            <div x-show="activeTab === 'dhd'" x-cloak class="space-y-5">
                <div class="flex items-center justify-between rounded-xl p-4" style="background:var(--input-bg);border:1px solid var(--border)">
                    <label class="text-sm font-bold" style="color:var(--text-secondary)">إرسال تلقائي للشحن</label>
                    <input type="checkbox" name="dhd_auto_send" value="1" {{ ($settings['dhd_auto_send'] ?? '') === '1' ? 'checked' : '' }} class="w-5 h-5 rounded cursor-pointer" style="accent-color:#4f8cff">
                </div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">API URL</label><input type="text" name="dhd_api_url" value="{{ old('dhd_api_url', $settings['dhd_api_url'] ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr" placeholder="https://api.dhd-dz.com">@error('dhd_api_url')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">API Token</label><input type="password" name="dhd_token" value="{{ old('dhd_token', $settings['dhd_token'] ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr">@error('dhd_token')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">الوزن الافتراضي (gram)</label><input type="number" name="dhd_default_weight" min="100" max="50000" value="{{ old('dhd_default_weight', $settings['dhd_default_weight'] ?? '1000') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)">@error('dhd_default_weight')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div class="flex items-center justify-between rounded-xl p-4" style="background:var(--input-bg);border:1px solid var(--border)"><label class="text-sm font-bold" style="color:var(--text-secondary)">يمكن فتحه (Can Open)</label><input type="checkbox" name="dhd_can_open" value="1" {{ ($settings['dhd_can_open'] ?? '1') === '1' ? 'checked' : '' }} class="w-5 h-5 rounded cursor-pointer" style="accent-color:#4f8cff"></div>
                <div class="flex items-center justify-between rounded-xl p-4" style="background:var(--input-bg);border:1px solid var(--border)"><label class="text-sm font-bold" style="color:var(--text-secondary)">هش / صطوك (Fragile)</label><input type="checkbox" name="dhd_is_fragile" value="1" {{ ($settings['dhd_is_fragile'] ?? '') === '1' ? 'checked' : '' }} class="w-5 h-5 rounded cursor-pointer" style="accent-color:#4f8cff"></div>
                <div>
                    <button type="button" @click="testing = true; testResult = null; $fetch('{{ route('dashboard.settings.testDhd') }}', { method: 'POST', headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}', 'Content-Type': 'application/json' } }).then(r => r.json()).then(d => { testResult = d; testing = false; }).catch(e => { testResult = { success: false, message: 'خطأ في الاتصال' }; testing = false; })" :disabled="testing" class="px-6 py-2.5 rounded-xl text-sm font-medium transition-colors disabled:opacity-50" style="background:var(--input-bg);color:var(--text-secondary)">
                        <span x-show="!testing">اختبار الاتصال</span><span x-show="testing" x-cloak>جاري الاختبار...</span>
                    </button>
                    <div x-show="testResult" x-cloak class="mt-3 p-3 rounded-xl text-sm" :class="testResult?.success ? '' : ''" :style="testResult?.success ? 'background:rgba(52,211,153,0.06);border:1px solid rgba(52,211,153,0.15);color:#34d399' : 'background:rgba(248,113,113,0.06);border:1px solid rgba(248,113,113,0.15);color:#f87171'" x-text="testResult?.message"></div>
                </div>
            </div>
            <div x-show="activeTab === 'telegram'" x-cloak class="space-y-5">
                <div class="rounded-xl p-4" style="background:rgba(79,140,255,0.06);border:1px solid rgba(79,140,255,0.15)">
                    <p class="font-medium mb-1" style="color:#4f8cff">إشعارات تيليجرام</p>
                    <p class="text-sm" style="color:var(--text-secondary)">سيتم إرسال إشعار لكل طلبية جديدة وتحديث الحالة عبر تيليجرام.</p>
                    <p class="mt-2 text-xs" style="color:var(--text-secondary)">1. تكلم مع <a href="https://t.me/BotFather" target="_blank" class="underline" style="color:#4f8cff">@BotFather</a> وأنشئ بوت</p>
                    <p class="text-xs" style="color:var(--text-secondary)">2. انسخ التوكن وضعه هنا</p>
                    <p class="text-xs" style="color:var(--text-secondary)">3. أرسل رسالة للبوت ثم تفقّد <a href="https://api.telegram.org/bot<TOKEN>/getUpdates" target="_blank" class="underline" style="color:#4f8cff">getUpdates</a> للحصول على Chat ID</p>
                </div>
                <div class="flex items-center justify-between rounded-xl p-4" style="background:var(--input-bg);border:1px solid var(--border)"><label class="text-sm font-bold" style="color:var(--text-secondary)">تفعيل الإشعارات</label><input type="checkbox" name="telegram_enabled" value="1" {{ ($settings['telegram_enabled'] ?? '0') === '1' ? 'checked' : '' }} class="w-5 h-5 rounded cursor-pointer" style="accent-color:#4f8cff"></div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">Bot Token</label><input type="text" name="telegram_bot_token" value="{{ old('telegram_bot_token', $settings['telegram_bot_token'] ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr" placeholder="1234567890:ABCdefGHIjklMNOpqrSTUvwxYZ">@error('telegram_bot_token')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">Chat ID</label><input type="text" name="telegram_chat_id" value="{{ old('telegram_chat_id', $settings['telegram_chat_id'] ?? '') }}" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" dir="ltr" placeholder="-1001234567890">@error('telegram_chat_id')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div>
                    <button type="button" @click="testingTg = true; testResultTg = null; $fetch('{{ route('dashboard.settings.testTelegram') }}', { method: 'POST', headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}', 'Content-Type': 'application/json' }, body: JSON.stringify({ token: document.querySelector('input[name=telegram_bot_token]').value, chat_id: document.querySelector('input[name=telegram_chat_id]').value }) }).then(r => r.json()).then(d => { testResultTg = d; testingTg = false; }).catch(e => { testResultTg = { success: false, message: 'خطأ في الاتصال' }; testingTg = false; })" :disabled="testingTg" class="px-6 py-2.5 rounded-xl text-sm font-medium transition-colors disabled:opacity-50" style="background:var(--input-bg);color:var(--text-secondary)">
                        <span x-show="!testingTg">اختبار الاتصال</span><span x-show="testingTg" x-cloak>جاري الاختبار...</span>
                    </button>
                    <div x-show="testResultTg" x-cloak class="mt-3 p-3 rounded-xl text-sm" :style="testResultTg?.success ? 'background:rgba(52,211,153,0.06);border:1px solid rgba(52,211,153,0.15);color:#34d399' : 'background:rgba(248,113,113,0.06);border:1px solid rgba(248,113,113,0.15);color:#f87171'" x-text="testResultTg?.message"></div>
                </div>
            </div>
            <div x-show="activeTab === 'account'" x-cloak class="space-y-5">
                <div class="rounded-xl p-4" style="background:var(--input-bg);border:1px solid var(--border)"><p class="text-sm" style="color:var(--text-secondary)">البريد الإلكتروني: <span class="text-white">{{ auth()->user()->email ?? '' }}</span></p></div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">كلمة المرور الحالية</label><input type="password" name="current_password" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" placeholder="اتركها فارغة إذا لا تريد التغيير">@error('current_password')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">كلمة المرور الجديدة</label><input type="password" name="new_password" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)" placeholder="اتركها فارغة إذا لا تريد التغيير">@error('new_password')<span class="text-sm mt-1 block" style="color:#f87171">{{ $message }}</span>@enderror</div>
                <div><label class="block text-sm font-bold mb-1.5" style="color:var(--text-secondary)">تأكيد كلمة المرور الجديدة</label><input type="password" name="new_password_confirmation" class="w-full rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-accent-blue" style="background:var(--input-bg);border:1px solid var(--border);color:var(--text-primary)"></div>
            </div>
            <div class="flex justify-end pt-6 border-t mt-6" style="border-color:var(--border)">
                <button type="submit" class="px-6 py-2.5 rounded-xl text-sm font-bold transition-all hover:scale-[1.02]" style="background:#111827;color:#ffffff">حفظ الإعدادات</button>
            </div>
        </form>
    </div>
</div>
@endsection
